<a href="https://colab.research.google.com/github/melnotte/data_science_specialization/blob/main/Pandas_E_S_trabajando_con_diferentes_formatos_de_archivo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> Este cuaderno contiene las actividades realizadas en el curso de
Pandas E/S: trabajando con diferentes formatos de archivo



In [ ]:
import pandas as pd
import chardet

In [ ]:
# Obtenemos la codificación del archivo
with open('datos_sus.csv', 'rb') as file:
  print(chardet.detect(file.read()))

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}


In [ ]:
df = pd.read_csv('datos_sus.csv', encoding = 'ISO-8859-1', sep = ';', skiprows = 2, skipfooter=9, engine='python')

In [ ]:
df.head()

Período:Jan/2008-Mar/2021
Unidade da Federação 2008/Jan   2008/Fev   2008/Mar   2008/Abr   2008/Mai   2008/Jun   2008/Jul   2008/Ago   2008/Set   2008/Out   2008/Nov   2008/Dez   2009/Jan   2009/Fev   2009/Mar   2009/Abr   2009/Mai   2009/Jun   2009/Jul   2009/Ago   2009/Set   2009/Out   2009/Nov   2009/Dez   2010/Jan   2010/Fev   2010/Mar   2010/Abr   2010/Mai   2010/Jun    2010/Jul    2010/Ago   2010/Set   2010/Out   2010/Nov   2010/Dez   2011/Jan   2011/Fev   2011/Mar   2011/Abr    2011/Mai    2011/Jun    2011/Jul    2011/Ago   2011/Set    2011/Out   2011/Nov   2011/Dez    2012/Jan    2012/Fev    2012/Mar    2012/Abr   2012/Mai    2012/Jun    2012/Jul    2012/Ago    2012/Set    2012/Out    2012/Nov    2012/Dez   2013/Jan    2013/Fev   2013/Mar    2013/Abr    2013/Mai    2013/Jun    2013/Jul    2013/Ago    2013/Set    2013/Out    2013/Nov    2013/Dez    2014/Jan    2014/Fev   2014/Mar   2014/Abr   2014/Mai    2014/Jun    2014/Jul   2014/Ago   2014/Set    2014/Out    2014/Nov    2014/Dez    2015/Jan    2015/Fev    2015/Mar    2015/Abr    2015/Mai    2015/Jun    2015/Jul    2015/Ago    2015/Set    2015/Out    2015/Nov    2015/Dez    2016/Jan    2016/Fev    2016/Mar    2016/Abr    2016/Mai    2016/Jun    2016/Jul    2016/Ago    2016/Set    2016/Out    2016/Nov    2016/Dez    2017/Jan    2017/Fev    2017/Mar    2017/Abr    2017/Mai    2017/Jun    2017/Jul    2017/Ago    2017/Set    2017/Out    2017/Nov    2017/Dez    2018/Jan    2018/Fev    2018/Mar    2018/Abr    2018/Mai    2018/Jun    2018/Jul    2018/Ago    2018/Set    2018/Out    2018/Nov    2018/Dez    2019/Jan    2019/Fev    2019/Mar    2019/Abr    2019/Mai    2019/Jun    2019/Jul    2019/Ago    2019/Set    2019/Out    2019/Nov    2019/Dez    2020/Jan    2020/Fev    2020/Mar    2020/Abr    2020/Mai    2020/Jun    2020/Jul    2020/Ago    2020/Set    2020/Out    2020/Nov    2020/Dez    2021/Jan    2021/Fev    2021/Mar                        Total
Rondônia             1388528,39 2931283,42 1541682,52 1525314,96 1645953,84 1406150,68 3065279,01 3231494,61 3117178,63 3068430,44 2825838,52 2931173,58 2885269,07 2860103,74 3684944,68 3607289,68 3774356,60 3706711,84 3763187,55 3533625,83 3605007,43 3907032,72 3939820,71 3901084,11 3684407,02 3623015,58 3890461,90 4193533,87 4534400,67 4451208,03  4874592,78  4460802,38 5067886,24 4511092,85 4394680,50 4098741,80 4411499,48 3868617,95 4298702,78 5062171,26  4769347,86  4578105,60  4477870,09  5173453,51 5554791,51  4110177,87 4428561,32 3534337,12  4015781,56  4426788,59  4873364,26  4516103,32 4619267,68  5226741,11  4756327,23  4112530,56  4023514,11  3866138,34  3543519,05  3201183,18 4072043,77  4534984,70 5229512,34  5660083,57  5681210,93  5076918,42  5623854,81  5928359,34  6019754,08  6050368,46  6422821,25  6172605,14  5773335,50  6229461,54 6536336,12 6611751,56 7122614,34  7207965,81  6725041,04 7220209,27 6814650,05  5931824,36  6179626,72  6743020,43  7278090,89  6619352,84  7131263,61  6945021,28  7868953,20  7546597,11  8738484,55  6756554,76  7443631,94  6964209,53  6310062,08  6561221,77  7735224,22  7995955,06  7189165,44  7956812,12  7551313,49  7930610,83  8133705,36  8150486,59  8022627,09  7280387,24  7047166,57  6961884,87  7820057,09  6801952,61  7825186,40  8706448,06  7700730,62  7948291,63  8438077,45  7656644,83  8047742,98  8657206,23  8150893,68  7507845,13  7998345,94  8893683,69  8867793,32  8871408,50  8501601,67  8315107,81  8525499,78  9177611,46  7368996,38  8835095,43  8328186,64  8408512,77  9351705,82  8143007,97  8949741,77  9630553,15  9581970,31  7891114,05  9792370,67  9170787,53  8816846,71  10024554,15 9675423,70  8085025,66  9222010,60  7493901,30  8148169,46  7353768,37  7739864,47  9246097,96  11824687,13 11733307,76 10201985,14 7955139,45  9357946,29  8880836,55  9266014,59  7730597,04  11023309,47              996411254,68
Acre                 902416,00  1497206,26 1794028,48 1730469,42 1819443,92 1828496,00 2511754,59 2089107,14 2275708,53 1923886,57 1756986,80 2235639,98 2497116

In [ ]:
df.shape

(29, 1)

# IMPORTAR A EXCEL

In [ ]:
archivo = 'emisiones_CO2.xlsx'

In [ ]:
data_co2 = pd.read_excel(archivo)

In [ ]:
data_co2.head()

País ISO 3166-1 alpha-3   Año  Total  Carbón  Aceite  Gas  Cemento  \
0  Afganistán                AFG  1750    0.0     NaN     NaN  NaN      NaN   
1  Afganistán                AFG  1751    0.0     NaN     NaN  NaN      NaN   
2  Afganistán                AFG  1752    0.0     NaN     NaN  NaN      NaN   
3  Afganistán                AFG  1753    0.0     NaN     NaN  NaN      NaN   
4  Afganistán                AFG  1754    0.0     NaN     NaN  NaN      NaN   

   Quema  Otros  Per Capita  
0    NaN    NaN         NaN  
1    NaN    NaN         NaN  
2    NaN    NaN         NaN  
3    NaN    NaN         NaN  
4    NaN    NaN         NaN

In [ ]:
pd.ExcelFile(archivo).sheet_names

['emisiones_C02', 'emisiones_percapita', 'fuentes']

In [ ]:
per_capita = pd.read_excel(archivo, sheet_name='emisiones_percapita')
per_capita.head()

País ISO 3166-1 alpha-3   Año  Total  Carbón  Aceite  Gas  Cemento  \
0  Afganistán                AFG  1750    NaN     NaN     NaN  NaN      NaN   
1  Afganistán                AFG  1751    NaN     NaN     NaN  NaN      NaN   
2  Afganistán                AFG  1752    NaN     NaN     NaN  NaN      NaN   
3  Afganistán                AFG  1753    NaN     NaN     NaN  NaN      NaN   
4  Afganistán                AFG  1754    NaN     NaN     NaN  NaN      NaN   

   Quema  Otros  
0    NaN    NaN  
1    NaN    NaN  
2    NaN    NaN  
3    NaN    NaN  
4    NaN    NaN

In [ ]:
per_capita.tail()

País ISO 3166-1 alpha-3   Año      Total     Carbón     Aceite  \
63099  Global                WLD  2017  4749682.0  1908857.0  1610910.0   
63100  Global                WLD  2018  4792753.0  1919213.0  1596350.0   
63101  Global                WLD  2019  4775633.0  1896468.0  1589920.0   
63102  Global                WLD  2020  4497423.0  1807760.0  1427353.0   
63103  Global                WLD  2021  4693699.0  1893923.0  1496614.0   

             Gas   Cemento    Quema    Otros  
63099   940144.0  198416.0  51579.0  39776.0  
63100   979965.0  204225.0  53634.0  39366.0  
63101   984878.0  208309.0  56569.0  39490.0  
63102   963695.0  208844.0  51981.0  37789.0  
63103  1001585.0  211472.0  52663.0  37443.0

In [ ]:
#Registros aleatorios
per_capita.sample(10)

País ISO 3166-1 alpha-3   Año      Total  Carbón     Aceite  \
4784          Barbados                BRB  1910        NaN     NaN        NaN   
19852  Guiana Francesa                GUF  2018  2540156.0     0.0  2540156.0   
7195          Botsuana                BWA  1873        NaN     NaN        NaN   
10966  Isla De Navidad                CXR  1836        NaN     NaN        NaN   
35217        Martinica                MTQ  1879        NaN     NaN        NaN   
11175         Colombia                COL  1773        NaN     NaN        NaN   
60706          Vanuatu                VUT  1800        NaN     NaN        NaN   
35309        Martinica                MTQ  1971  1635504.0     0.0  1635504.0   
51461    Islas Salomón                SLB  1803        NaN     NaN        NaN   
44257          Polonia                POL  1943        NaN     NaN        NaN   

       Gas  Cemento  Quema  Otros  
4784   NaN      NaN    NaN    NaN  
19852  0.0      0.0    0.0    NaN  
7195   NaN      NaN    NaN    NaN  
10966  NaN      NaN    NaN    NaN  
35217  NaN      NaN    NaN    NaN  
11175  NaN      NaN    NaN    NaN  
60706  NaN      NaN    NaN    NaN  
35309  0.0      0.0    0.0    NaN  
51461  NaN      NaN    NaN    NaN  
44257  NaN      NaN    NaN    NaN

In [ ]:
emisiones_C02 = pd.read_excel(archivo, sheet_name='emisiones_C02', usecols = 'A:D', nrows = 10)
emisiones_C02

País ISO 3166-1 alpha-3   Año  Total
0  Afganistán                AFG  1750      0
1  Afganistán                AFG  1751      0
2  Afganistán                AFG  1752      0
3  Afganistán                AFG  1753      0
4  Afganistán                AFG  1754      0
5  Afganistán                AFG  1755      0
6  Afganistán                AFG  1756      0
7  Afganistán                AFG  1757      0
8  Afganistán                AFG  1758      0
9  Afganistán                AFG  1759      0

# EXPORTAR A EXCEL


In [ ]:
per_capita.to_excel('co2_per_capita.xlsx', index = False)

In [ ]:
pd.read_excel('co2_per_capita.xlsx')

País ISO 3166-1 alpha-3   Año      Total     Carbón     Aceite  \
0      Afganistán                AFG  1750        NaN        NaN        NaN   
1      Afganistán                AFG  1751        NaN        NaN        NaN   
2      Afganistán                AFG  1752        NaN        NaN        NaN   
3      Afganistán                AFG  1753        NaN        NaN        NaN   
4      Afganistán                AFG  1754        NaN        NaN        NaN   
...           ...                ...   ...        ...        ...        ...   
63099      Global                WLD  2017  4749682.0  1908857.0  1610910.0   
63100      Global                WLD  2018  4792753.0  1919213.0  1596350.0   
63101      Global                WLD  2019  4775633.0  1896468.0  1589920.0   
63102      Global                WLD  2020  4497423.0  1807760.0  1427353.0   
63103      Global                WLD  2021  4693699.0  1893923.0  1496614.0   

             Gas   Cemento    Quema    Otros  
0            NaN       NaN      NaN      NaN  
1            NaN       NaN      NaN      NaN  
2            NaN       NaN      NaN      NaN  
3            NaN       NaN      NaN      NaN  
4            NaN       NaN      NaN      NaN  
...          ...       ...      ...      ...  
63099   940144.0  198416.0  51579.0  39776.0  
63100   979965.0  204225.0  53634.0  39366.0  
63101   984878.0  208309.0  56569.0  39490.0  
63102   963695.0  208844.0  51981.0  37789.0  
63103  1001585.0  211472.0  52663.0  37443.0  

[63104 rows x 10 columns]

# IMPORTAR DESDE GOOGLE SHEETS

In [ ]:
sheet_id = '1siatjK8J5J3FFJlzppPCWlwC7TU3yaTm4-xkycpF7ZU'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
global_carbon_emissions = pd.read_csv(url)
global_carbon_emissions

Country Name country_code                      Region  \
0           Aruba          ABW   Latin America & Caribbean   
1     Afghanistan          AFG                  South Asia   
2          Angola          AGO          Sub-Saharan Africa   
3         Albania          ALB       Europe & Central Asia   
4         Andorra          AND       Europe & Central Asia   
..            ...          ...                         ...   
210         Samoa          WSM         East Asia & Pacific   
211   Yemen, Rep.          YEM  Middle East & North Africa   
212  South Africa          ZAF          Sub-Saharan Africa   
213        Zambia          ZMB          Sub-Saharan Africa   
214      Zimbabwe          ZWE          Sub-Saharan Africa   

                             Indicator Name           1990           1991  \
0    CO2 emissions (metric tons per capita)            NaN            NaN   
1    CO2 emissions (metric tons per capita)    191,745,115    167,681,579   
2    CO2 emissions (metric tons per capita)    553,661,955    544,538,649   
3    CO2 emissions (metric tons per capita)  1,819,541,634    124,281,022   
4    CO2 emissions (metric tons per capita)  7,521,831,658    723,537,924   
..                                      ...            ...            ...   
210  CO2 emissions (metric tons per capita)     55,283,574    609,756,098   
211  CO2 emissions (metric tons per capita)     56,703,735    690,937,429   
212  CO2 emissions (metric tons per capita)  6,729,798,587  6,424,621,766   
213  CO2 emissions (metric tons per capita)    340,929,635    349,232,211   
214  CO2 emissions (metric tons per capita)  1,585,443,976  1,713,321,439   

              1992           1993           1994           1995  ...  \
0              NaN            NaN            NaN            NaN  ...   
1       95,957,742      8,472,111     75,545,827     68,467,956  ...   
2      543,557,223     70,898,423    836,804,405    912,141,485  ...   
3      683,699,826    638,307,036    645,355,189    605,436,253  ...   
4       69,630,787  6,724,177,518  6,541,578,914  6,733,479,486  ...   
..             ...            ...            ...            ...  ...   
210    604,266,119    658,221,486    592,806,881    705,674,802  ...   
211    704,793,064    627,104,927    653,255,714    706,080,534  ...   
212  6,175,429,944  6,219,193,872  6,215,847,077  6,378,789,568  ...   
213     33,722,439    289,956,061    241,269,619    234,153,214  ...   
214  1,694,415,977  1,539,740,958  1,417,186,242    135,661,892  ...   

              2011           2012           2013           2014  \
0              NaN            NaN            NaN            NaN   
1       29,650,624    259,295,334     18,562,366    146,235,617   
2      985,522,312    950,695,879  1,036,293,852  1,099,779,111   
3      166,942,319    150,324,046  1,533,630,039  1,668,337,371   
4    5,850,886,105  5,944,654,173  5,942,800,412  5,807,127,723   
..             ...            ...            ...            ...   
210  1,066,843,067  1,057,703,002  1,048,701,723  1,092,498,145   
211    963,978,488    858,490,955  1,106,687,715  1,062,211,282   
212  7,869,815,906  8,077,957,969  8,138,264,312  8,212,241,156   
213    217,496,732     27,860,069    284,057,568    304,549,552   
214     88,488,553    915,734,944    919,824,123    889,104,126   

              2015           2016           2017           2018  \
0              NaN            NaN            NaN            NaN   
1      172,896,741    149,789,334    131,694,556      1,632,953   
2      113,504,405  1,031,811,348     81,330,073    777,674,934   
3      160,377,515  1,557,664,358  1,788,786,074  1,782,738,948   
4    6,026,181,822  6,080,600,282  6,104,133,912  6,362,975,399   
..             ...            ...            ...            ...   
210  1,240,245,954  1,542,099,372  1,586,830,344  1,478,626,161   
211    511,361,652    399,363,829    359,621,635    341,068,402   
212  7,669,937,662  7,563,739,495  7,641,675,086  7,515,678,60

In [ ]:
global_carbon_emissions.to_csv('global_carbon_emissions.csv', index=False)

#IMPORTAR JSON DESDE API

In [ ]:
!pip install requests

In [ ]:
import requests
import json

In [ ]:
datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')

In [ ]:
tutti_frutti = json.loads(datos_frutas.text)

In [ ]:
tutti_frutti_normalized = pd.json_normalize(tutti_frutti)
tutti_frutti_normalized

name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

    nutritions.ca

# IMPORTAR HTML

In [ ]:
html_data = pd.read_html('peliculas_wikipedia.html')
html_data

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                             Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   

In [ ]:
type(html_data)

list

In [ ]:
len(html_data)

3

In [ ]:
#Extraer la segunda tabla
top_100_movies = html_data[1]
top_100_movies

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

# EXPORTAR A HTML


In [ ]:
top_100_movies.to_html('top_100_movies.html', index=False)

In [ ]:
pd.read_html('top_100_movies.html')

[                            Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   ...   
 95                 The Searchers          1956             John Ford   
 96              Bringing Up Baby          1938          Howard Hawks   
 97                    Unforgiven          1992        Clint Eastwood   
 98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
 99           Yankee Doodle Dandy          1942        Michael Curtiz   
 
                       Production companies  Rank  
 0                       RKO Radio Pictures     1  
 1                

In [ ]:
top_100_movies.to_csv('top_100_movies.csv', index=False)

In [ ]:
pd.read_csv('top_100_movies.csv')

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

# IMPORTAR/EXPORTAR XML

In [ ]:
imdb_data = pd.read_xml('imdb_top_1000.xml')
imdb_data.head(5)

index                                        Poster_Link  \
0      0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1      1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2      2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3      3  https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4      4  https://m.media-amazon.com/images/M/MV5BMWU4N2...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   
3    The Godfather: Part II          1974           A  202 min   
4              12 Angry Men          1957           U   96 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   
3          Crime, Drama          9.0   
4          Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   
3  The early life and career of Vito Corleone in ...        90.0   
4  A jury holdout attempts to prevent a miscarria...        96.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   
3  Francis Ford Coppola       Al Pacino  Robert De Niro  Robert Duvall   
4          Sidney Lumet     Henry Fonda     Lee J. Cobb  Martin Balsam   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444  
3    Diane Keaton      1129952   57,300,000  
4    John Fiedler       689845    4,360,000

In [ ]:
imdb_data.to_xml('imdb_movies_data.xml', index=False)

In [ ]:
pd.read_xml('imdb_movies_data.xml')

index                                        Poster_Link  \
0        0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1        1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2        2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3        3  https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4        4  https://m.media-amazon.com/images/M/MV5BMWU4N2...   
..     ...                                                ...   
995    995  https://m.media-amazon.com/images/M/MV5BNGEwMT...   
996    996  https://m.media-amazon.com/images/M/MV5BODk3Yj...   
997    997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...   
998    998  https://m.media-amazon.com/images/M/MV5BZTBmMj...   
999    999  https://m.media-amazon.com/images/M/MV5BMTY5OD...   

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min   
1               The Godfather          1972           A  175 min   
2             The Dark Knight          2008          UA  152 min   
3      The Godfather: Part II          1974           A  202 min   
4                12 Angry Men          1957           U   96 min   
..                        ...           ...         ...      ...   
995    Breakfast at Tiffany's          1961           A  115 min   
996                     Giant          1956           G  201 min   
997     From Here to Eternity          1953      Passed  118 min   
998                  Lifeboat          1944        None   97 min   
999              The 39 Steps          1935        None   86 min   

                        Genre  IMDB_Rating  \
0                       Drama          9.3   
1                Crime, Drama          9.2   
2        Action, Crime, Drama          9.0   
3                Crime, Drama          9.0   
4                Crime, Drama          9.0   
..                        ...          ...   
995    Comedy, Drama, Romance          7.6   
996            Drama, Western          7.6   
997       Drama, Romance, War          7.6   
998                Drama, War          7.6   
999  Crime, Mystery, Thriller          7.6   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    When the menace known as the Joker wreaks havo...        84.0   
3    The early life and career of Vito Corleone in ...        90.0   
4    A jury holdout attempts to prevent a miscarria...        96.0   
..                                                 ...         ...   
995  A young New York socialite becomes interested ...        76.0   
996  Sprawling epic covering the life of a Texas ca...        84.0   
997  In Hawaii in 1941, a private is cruelly punish...        85.0   
998  Several survivors of a torpedoed merchant ship...        78.0   
999  A man in London tries to help a counter-espion...        93.0   

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman   
1    Francis Ford Coppola      Marlon Brando          Al Pacino   
2       Christopher Nolan     Christian Bale       Heath Ledger   
3    Francis Ford Coppola          Al Pacino     Robert De Niro   
4            Sidney Lumet        Henry Fonda        Lee J. Cobb   
..                    ...                ...                ...   
995         Blake Edwards     Audrey Hepburn     George Peppard   
996        George Stevens   Elizabeth Taylor        Rock Hudson   
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift   
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak   
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll   

              Star3           Star4  No_of_Votes        Gross  
0        Bob Gunton  William Sadler      2343110   28,341,469  
1        James Caan    Diane Keaton      1620367  134,966,411  
2     Aaron Eckh

#**Desafío**: obtener un DataFrame de la tabla que contiene la información del número de habitantes de cada país.

In [ ]:
url = 'https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n'

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

response = requests.get(url, headers=headers)
pob_data = pd.read_html(response.text)

/tmp/ipython-input-1267405142.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pob_data = pd.read_html(response.text)


In [ ]:
pob_data

[     N.º                   País (o territorio dependiente)  \
 0      1                                             India   
 1      2                                        China[12]​   
 2      3                                    Estados Unidos   
 3      4                                         Indonesia   
 4      5                                          Pakistán   
 ..   ...                                               ...   
 241  242                           Islas Cocos (Australia)   
 242  243  Islas Ultramarinas Menores de los Estados Unidos   
 243  244                               Islas Pitcairn (RU)   
 244  NaN                                             Mundo   
 245   N°                   País (o territorio dependiente)   
 
     Proyección exponencial de la población al 1/7/2025[7]​  \
 0                                        1 417 492 000       
 1                                        1 407 934 000       
 2                                          342 181 0

In [ ]:
pob_data[3]

N.º País (o territorio dependiente)  \
0      1                           China   
1      2                           India   
2      3                  Estados Unidos   
3      4                           Rusia   
4      5                           Japón   
..   ...                             ...   
233  234         San Bartolomé (Francia)   
234  235                    Tokelau (NZ)   
235  236             Ciudad del Vaticano   
236  237                 San Martín (PB)   
237    -                           Mundo   

    Población estimada por la ONU para mediados del año  1950  \
0                                          543 979 000          
1                                          357 021 000          
2                                          148 282 000          
3                                          102 580 000          
4                                           84 353 000          
..                                                 ...          
233                                              2 000          
234                                              2 000          
235                                              1 000          
236                                              1 000          
237                                  2 499 327 000 000          

     % del total mundial  
0                   2177  
1                   1428  
2                    593  
3                    410  
4                    338  
..                   ...  
233                    0  
234                    0  
235                    0  
236                    0  
237                10000  

[238 rows x 4 columns]

#BASE DE DATOS LOCAL

In [ ]:
import sqlalchemy

In [ ]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [ ]:
# Creando el motor SQLite
engine = create_engine('sqlite:///:memory:')

In [ ]:
file = 'clientes_banco.csv'

In [ ]:
clientes = pd.read_csv(file)
clientes.head()

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0     5008804    32    Nivel superior  Relación-estable               2   
1     5008805    32    Nivel superior  Relación-estable               2   
2     5008806    58  Nivel intermedio            Casado               2   
3     5008808    52  Nivel intermedio           Soltero               1   
4     5008809    52  Nivel intermedio           Soltero               1   

  Categoria_de_renta  Ocupacion  Años_empleado  Rendimiento_anual  \
0           Empleado       Otro             12           427500.0   
1           Empleado       Otro             12           427500.0   
2           Empleado  Seguridad              3           112500.0   
3   Business Partner     Ventas              8           270000.0   
4   Business Partner     Ventas              8           270000.0   

   Tiene_carro                  Vivienda  
0            1    Departamento alquilado  
1            1    Departamento alquilado  
2            1  Casa/Departamento propio  
3            0  Casa/Departamento propio  
4            0  Casa/Departamento propio

In [ ]:
clientes.shape

(438463, 11)

## CREATE

In [ ]:
clientes.to_sql('clientes', con=engine, index=False)

438463

In [ ]:
inspector = inspect(engine)

In [ ]:
print(inspector.get_table_names())

['clientes', 'empleados']


In [ ]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renta = "Empleado"'

In [ ]:
empleados = pd.read_sql_query(sql=text(query), con=engine.connect())

In [ ]:
type(empleados)

pandas.core.frame.DataFrame

In [ ]:
empleados

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008815    46    Nivel superior            Casado               2   
4          5112956    46    Nivel superior            Casado               2   
...            ...   ...               ...               ...             ...   
226054     6837905    43  Nivel intermedio            Casado               3   
226055     6837906    43  Nivel intermedio            Casado               3   
226056     6839936    34  Nivel intermedio            Casado               3   
226057     6840222    43  Nivel intermedio           Soltero               1   
226058     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3                Empleado        Contabilidad              2   
4                Empleado        Contabilidad              2   
...                   ...                 ...            ...   
226054           Empleado                Otro              7   
226055           Empleado                Otro              7   
226056           Empleado  Construcción Civil              5   
226057           Empleado  Construcción Civil              8   
226058           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            1  Casa/Departamento propio  
4                270000.0            1  Casa/Departamento propio  
...                   ...          ...                       ...  
226054           355050.0            1  Casa/Departamento propio  
226055           355050.0            1  Casa/Departamento propio  
226056           135000.0            1  Casa/Departamento propio  
226057           103500.0            0  Casa/Departamento propio  
226058           121500.0            0  Casa/Departamento propio  

[226059 rows x 11 columns]

In [ ]:
empleados.to_sql('empleados', con=engine.connect(), index=False,)

226059

## READ


In [ ]:
pd.read_sql_table('empleados', con=engine.connect(), columns=['ID_Cliente','Grado_estudio','Rendimiento_anual'])

ID_Cliente     Grado_estudio  Rendimiento_anual
0          5008804    Nivel superior           427500.0
1          5008805    Nivel superior           427500.0
2          5008806  Nivel intermedio           112500.0
3          5008815    Nivel superior           270000.0
4          5112956    Nivel superior           270000.0
...            ...               ...                ...
226054     6837905  Nivel intermedio           355050.0
226055     6837906  Nivel intermedio           355050.0
226056     6839936  Nivel intermedio           135000.0
226057     6840222  Nivel intermedio           103500.0
226058     6842885  Nivel intermedio           121500.0

[226059 rows x 3 columns]

## DELETE


In [ ]:
query = 'SELECT * FROM clientes'

In [ ]:
pd.read_sql(sql=text(query), con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           135000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

In [ ]:
from sqlalchemy.exc import  SQLAlchemyError
query = 'DELETE FROM clientes WHERE ID_Cliente = 5008804'
try:
  r_set = engine.connect().execute(text(query))

except SQLAlchemyError as e:
    print(e)
else:
  print("#Records deleted: ", r_set.rowcount)

#Records deleted:  1


In [ ]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008805    32    Nivel superior  Relación-estable               2   
1          5008806    58    Nivel superior            Casado               2   
2          5008808    52  Nivel intermedio           Soltero               1   
3          5008809    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438457     6840104    62  Nivel intermedio        Divorciado               1   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado           Seguridad              3   
2        Business Partner              Ventas              8   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438457        Pensionista                Otro              0   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                112500.0            1  Casa/Departamento propio  
2                270000.0            0  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           135000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

## UPDATE

In [ ]:
from sqlalchemy.exc import  SQLAlchemyError
query = 'UPDATE clientes SET Grado_estudio = "Nivel superior" WHERE ID_Cliente = 5008806'
try:
  r_set = engine.connect().execute(text(query))

except SQLAlchemyError as e:
    print(e)
else:
  print("#Records updated: ", r_set.rowcount)

#Records updated:  1


#**Desafío**: crear una base de datos local de clientes para una institución financiera.

In [ ]:
# Creando el motor SQLite
engine2 = create_engine('sqlite:///:memory:')

In [ ]:
file = 'clientes_banco.csv'

In [ ]:
clientes_banco = pd.read_csv(file)

In [ ]:
clientes_banco.to_sql('clientes_banco', con=engine2, index=False)

438463

In [ ]:
inspector = inspect(engine2)

In [ ]:
print(inspector.get_table_names())

['clientes_banco']


In [ ]:
clientes_banco

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           135000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

1. Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.


In [ ]:
query = 'SELECT ID_Cliente, Rendimiento_anual FROM clientes_banco WHERE ID_Cliente = 6840104'

In [ ]:
cliente = pd.read_sql_query(sql=text(query), con=engine2.connect())
cliente

ID_Cliente  Rendimiento_anual
0     6840104           300000.0

In [ ]:
query = 'UPDATE clientes_banco SET Rendimiento_anual = 300000 WHERE ID_Cliente = 6840104'
try:
  r_set = engine2.connect().execute(text(query))

except SQLAlchemyError as e:
    print(e)
else:
  print("#Records updated: ", r_set.rowcount)

#Records updated:  1


2. Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.

In [ ]:
query = 'DELETE FROM clientes_banco WHERE ID_Cliente = 5008809'
try:
  r_set = engine2.connect().execute(text(query))

except SQLAlchemyError as e:
    print(e)
else:
  print("#Records deleted: ", r_set.rowcount)

#Records deleted:  1


In [ ]:
query = 'SELECT ID_Cliente, Rendimiento_anual FROM clientes_banco WHERE ID_Cliente = 5008809'

In [ ]:
cliente = pd.read_sql_query(sql=text(query), con=engine2.connect())
cliente

Empty DataFrame
Columns: [ID_Cliente, Rendimiento_anual]
Index: []

Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:
* ID_cliente: 6850985
* Edad: 33
* Grado_estudio: Doctorado
* Estado_civil: Soltero
* Tamaño_familia: 1
* Categoria_de_renta: Empleado
* Ocupacion: TI
* Años_empleado: 2
* Rendimiento_anual: 290000
* Tiene_carro: 0
* Vivienda: Casa/Departamento propio

In [ ]:
query = 'INSERT INTO clientes_banco(ID_Cliente, Edad, Grado_estudio, Estado_civil, Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, Rendimiento_anual, Tiene_carro, Vivienda) VALUES(6850985, 33, "Doctorado", "Soltero", 1, "Empleado", "TI", 2, 290000, 0, "Casa/Departamento propio")'
try:
  r_set = engine2.connect().execute(text(query))

except SQLAlchemyError as e:
    print(e)
else:
  print("#Records created: ", r_set.rowcount)

#Records created:  1


In [ ]:
query = 'SELECT ID_Cliente, Edad, Grado_estudio, Estado_civil, Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, Rendimiento_anual, Tiene_carro, Vivienda FROM clientes_banco WHERE ID_Cliente = 6850985'

In [ ]:
cliente = pd.read_sql_query(sql=text(query), con=engine2.connect())
cliente

ID_Cliente  Edad Grado_estudio Estado_civil  Tamaño_familia  \
0     6850985    33     Doctorado      Soltero               1   

  Categoria_de_renta Ocupacion  Años_empleado  Rendimiento_anual  Tiene_carro  \
0           Empleado        TI              2           290000.0            0   

                   Vivienda  
0  Casa/Departamento propio